remote: true

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - Product Manager
  - Technical Product Manager
  - Associate Product Manager

locations:
  - India
  

distance: 100

companyBlacklist:
  - platter
  - consciousleap
  - pluto

titleBlacklist:
  - sales
  - sales and target
